### ISSUE TITLE
Does not convert "type: null" correctly in most common use case. 

### ISSUE THREAD

**Issue by dskvr** [philsturgeon/json-schema-to-openapi-schema#21]
_Written in yaml because json is exhausting_ 

```
someObject: 
  type: object 
  property: 
    nullableProperty: 
      oneOf:
        - type: "null"
        - type: object 
          properties: 
            yay: 
              type: string 
```

Resulting output (Incorrect )

```
someObject: 
  type: object 
  property: 
    nullableProperty: 
      oneOf:
        - nullable: true
        - type: object 
          properties: 
            yay: 
              type: string 
```

Expected Output (correct)

```
someObject: 
  type: object 
  property: 
    nullableProperty: 
      type: object 
      nullable: true
      properties: 
        yay: 
          type: string 
````

While this will validate (loosely) against Swagger 3.0 specification, it will indeed break code generators.
